trigger:
  branches:
    include:
    - main
    - release/*
    - feature/*
  tags:
    include:
    - abstractions-extension-v*
    - ext-abstractions-v*
  paths:
    include:
    - src/extensions/Worker.Extensions.Abstractions/

extends:
  template: ../../../eng/ci/templates/extensions-ci.yml
  parameters:
    ExtensionDirectory: src/extensions/Worker.Extensions.Abstractions
