trigger:
  branches:
    include:
    - main
    - release/*
    - feature/*
  paths:
    include:
    - src/extensions/Worker.Extensions.Timer/

pr:
  branches:
    include:
    - main
    - release/*
    - feature/*
  paths:
    include:
    - src/extensions/Worker.Extensions.Timer/

extends:
  template: ../../../eng/ci/templates/extensions-ci.yml
  parameters:
    ExtensionDirectory: src/extensions/Worker.Extensions.Timer
