trigger:
  branches:
    include:
    - main
    - release/*
    - feature/*
  tags:
    include:
    - v*
  paths:
    include:
    - eng/
    - src/Worker

pr:
  branches:
    include:
    - main
    - release/*
    - feature/*
  paths:
    include:
    - eng/
    - samples
    - src/Worker
    - test/Worker
    - test/TestUtility
